create database diseaseSurvival;

create table diseases (
 name varchar(255) NOT NULL,
 condition varchar(255),
 id int NOT NULL identity(1,1),
 mortality varchar(255),
 constraint pk_diseases primary key(id)
);

insert into diseases (name) values ('African trypanosomiasis');
insert into diseases (name) values ('AIDS/HIV infection');
insert into diseases (name) values ('Anthrax, cutaneous');
insert into diseases (name) values ('Anthrax, gastorintestinal, intestinal type');
insert into diseases (name) values ('Anthrax, gastrointestinal, oropharyngeal type');
insert into diseases (name) values ('Anthrax, specifically the pulmonary form');
insert into diseases (name) values ('Asian (1956–58) flu');
insert into diseases (name) values ('Aspergillosis, invasive pulmonary form');
insert into diseases (name) values ('Botulism');
insert into diseases (name) values ('Brucellosis, untreated');
insert into diseases (name) values ('Bubonic plague');
insert into diseases (name) values ('Bubonic plague, untreated');
insert into diseases (name) values ('Dengue fever (DF)');
insert into diseases (name) values ('Dengue haemorrhagic fever (DHF)');
insert into diseases (name) values ('Diphtheria, respiratory');
insert into diseases (name) values ('Eastern equine encephalitis virus');
insert into diseases (name) values ('Ebola virus disease, Bundibugyo variant (BDBV)');
insert into diseases (name) values ('Ebola virus disease (for all types of ebolavirus outbreaks combined)');
insert into diseases (name) values ('Ebola virus disease — specifically EBOV "strain" (formerly Zaire Ebola virus)');
insert into diseases (name) values ('Ebola virus disease, Sudan variant (SUDV)');
insert into diseases (name) values ('Glanders, septicemic');
insert into diseases (name) values ('Glanders, septicemic');
insert into diseases (name) values ('Granulomatous amoebic encephalitis, Balamuthia mandrillaris & Acanthamoeba');
insert into diseases (name) values ('Hand, foot and mouth disease, children < 5 years old');
insert into diseases (name) values ('Hepatitis A');
insert into diseases (name) values ('Hepatitis A, adults > 50 years old');
insert into diseases (name) values ('Herpes B virus disease');
insert into diseases (name) values ('Hong Kong (1968–69) flu');
insert into diseases (name) values ('Influenza A, typical pandemics');
insert into diseases (name) values ('Influenza A virus subtype H5N1');
insert into diseases (name) values ('Intestinal capillariasis, untreated');
insert into diseases (name) values ('Lassa Fever');
insert into diseases (name) values ('Legionellosis');
insert into diseases (name) values ('Leptospirosis');
insert into diseases (name) values ('Lujo virus disease');
insert into diseases (name) values ('Malaria');
insert into diseases (name) values ('Marburg virus disease - all outbreaks combined');
insert into diseases (name) values ('Measles (rubeola), in developing countries');
insert into diseases (name) values ('Meningococcal disease');
insert into diseases (name) values ('Middle Eastern Respiratory Syndrome');
insert into diseases (name) values ('Mumps encephalitis');
insert into diseases (name) values ('Pertussis (whooping cough), children, unvaccinated, in developing countries');
insert into diseases (name) values ('Pertussis (whooping cough), infants, unvaccinated, in developing countries');
insert into diseases (name) values ('Plague, pneumonic');
insert into diseases (name) values ('Plague, septicemic');
insert into diseases (name) values ('Plague — specifically the septicemic or pneumonic type');
insert into diseases (name) values ('Primary amoebic meningoencephalitis, Naegleria fowleri');
insert into diseases (name) values ('Prion diseases, or transmissible spongiform encephalopathies (TSE)');
insert into diseases (name) values ('Progeria');
insert into diseases (name) values ('Rabies');
insert into diseases (name) values ('Reyes Syndrome');
insert into diseases (name) values ('Severe acute respiratory syndrome (SARS)');
insert into diseases (name) values ('Smallpox, Variola major — in pregnant women');
insert into diseases (name) values ('Smallpox Variola major — specifically the malignant (flat) or hemorrhagic type');
insert into diseases (name) values ('Smallpox, Variola major — unvaccinated');
insert into diseases (name) values ('Smallpox, Variola major — vaccinated');
insert into diseases (name) values ('Smallpox, Variola minor — unvaccinated');
insert into diseases (name) values ('Spanish (1918) flu');
insert into diseases (name) values ('Tuberculosis, untreated pulmonary, HIV-negative');
insert into diseases (name) values ('Tularemia pneumonia, untreated');
insert into diseases (name) values ('Tularemia, typhoidal');
insert into diseases (name) values ('Tularemia, typhoidal, untreated');
insert into diseases (name) values ('Typhoid fever');
insert into diseases (name) values ('Typhoid fever, untreated');
insert into diseases (name) values ('Varicella (chickenpox), adults');
insert into diseases (name) values ('Varicella (chickenpox), children');
insert into diseases (name) values ('Varicella (chickenpox), newborns, untreated');
insert into diseases (name) values ('Venezuelan Equine Encephalitis (VEE)');
insert into diseases (name) values ('Visceral leishmaniasis');
insert into diseases (name) values ('Visceral leishmaniasis');
insert into diseases (name) values ('Yellow fever');
update diseases set mortality= '~ 100%', condition='Untreated' where id=1;
update diseases set mortality= '80–90%', condition='Untreated' where id=2;
update diseases set mortality= '< 1%', condition='' where id=3;
update diseases set mortality= '> 50%', condition='' where id=4;
update diseases set mortality= '10–50%', condition='' where id=5;
update diseases set mortality= '> 85%', condition='Untreated' where id=6;
update diseases set mortality= '~ 0.1%', condition='' where id=7;
update diseases set mortality= '50–90%', condition='' where id=8;
update diseases set mortality= '< 10%', condition='' where id=9;
update diseases set mortality= '≤ 2%', condition='Untreated' where id=10;
update diseases set mortality= '< 5%', condition='' where id=11;
update diseases set mortality= '≤ 60%', condition='Untreated' where id=12;
update diseases set mortality= '1–5%', condition='Untreated' where id=13;
update diseases set mortality= '26%', condition='Untreated' where id=14;
update diseases set mortality= '~ 5–10%', condition='' where id=15;
update diseases set mortality= '~ 33%', condition='' where id=16;
update diseases set mortality= '~ 32%', condition='' where id=17;
update diseases set mortality= '25–90% (50% on average)', condition='' where id=18;
update diseases set mortality= '~ 83%, up to 90%', condition='' where id=19;
update diseases set mortality= '~ 54%', condition='' where id=20;
update diseases set mortality= '50%', condition='' where id=21;
update diseases set mortality= '95%', condition='Untreated' where id=22;
update diseases set mortality= '≥ 90%', condition='None' where id=23;
update diseases set mortality= '0.01%', condition='' where id=24;
update diseases set mortality= '0.1–0.3%', condition='' where id=25;
update diseases set mortality= '~ 1.8%', condition='' where id=26;
update diseases set mortality= '≤ 70%', condition='' where id=27;
update diseases set mortality= '~ 0.1%', condition='' where id=28;
update diseases set mortality= '< 0.1%', condition='' where id=29;
update diseases set mortality= '~ 60%', condition='' where id=30;
update diseases set mortality= '~ 10%', condition='Untreated' where id=31;
update diseases set mortality= '~ 1%', condition='' where id=32;
update diseases set mortality= '~ 15%', condition='' where id=33;
update diseases set mortality= '< 5–30%', condition='' where id=34;
update diseases set mortality= '80%', condition='' where id=35;
update diseases set mortality= '~ 0.3%', condition='' where id=36;
update diseases set mortality= '23%-90%', condition='' where id=37;
update diseases set mortality= '~ 1–3%', condition='' where id=38;
update diseases set mortality= '10–20%', condition='' where id=39;
update diseases set mortality= '~ 45%', condition='' where id=40;
update diseases set mortality= '~ 1%', condition='' where id=41;
update diseases set mortality= '~ 1%', condition='Unvaccinated' where id=42;
update diseases set mortality= '~ 3.7%', condition='Unvaccinated' where id=43;
update diseases set mortality= '50%', condition='' where id=44;
update diseases set mortality= '30–50%', condition='' where id=45;
update diseases set mortality= '~ 100%', condition='Untreated' where id=46;
update diseases set mortality= '~ 100%', condition='None' where id=47;
update diseases set mortality= '100%', condition='None' where id=48;
update diseases set mortality= '100%', condition='None' where id=49;
update diseases set mortality= '~ 100%', condition='Untreated / Vaccine exists' where id=50;
update diseases set mortality= '> 40%', condition='' where id=51;
update diseases set mortality= '11%', condition='' where id=52;
update diseases set mortality= '> 65%', condition='' where id=53;
update diseases set mortality= '~ 95%', condition='Untreated' where id=54;
update diseases set mortality= '30%', condition='Unvaccinated' where id=55;
update diseases set mortality= '3%', condition='Vaccinated' where id=56;
update diseases set mortality= '1%', condition='Unvaccinated' where id=57;
update diseases set mortality= '> 2.5%', condition='' where id=58;
update diseases set mortality= '43%', condition='' where id=59;
update diseases set mortality= '≤ 60%', condition='Untreated' where id=60;
update diseases set mortality= '~ 3–5%', condition='' where id=61;
update diseases set mortality= '~ 35%', condition='Untreated' where id=62;
update diseases set mortality= '< 1%', condition='' where id=63;
update diseases set mortality= '10–20%', condition='Untreated' where id=64;
update diseases set mortality= '0.02%', condition='' where id=65;
update diseases set mortality= '0.001%', condition='' where id=66;
update diseases set mortality= '~ 30%', condition='Untreated' where id=67;
update diseases set mortality= '< 1%', condition='' where id=68;
update diseases set mortality= '~ 10%', condition='' where id=69;
update diseases set mortality= '~ 100%', condition='Untreated' where id=70;
update diseases set mortality= '7.5%', condition='' where id=71;
